export const state = {
    isLoggedIn: false,
    isLoading: false,
    loginError: '',
    user: '',
    agent: {},
    postAgentLoading: '',
    postAgentError: "",
    isAgentPosted: false,
    agents: [],
    agentsLoading: false,
    agentsError: '',
    deleteAgentStatus: false,
    deleteError: "",
    updateAgentStatus: false,
    updateError: "",
    addRiderStatus: false,
    addRiderError: "",
    riders: [],
    riders_loaing: false,
    riders_error: "",
    deleteBodabodaStatus: false,
    deleteBodabodaError: "",
    updateBodabodaStatus: false,
    updateBodabodaError: "",
    addLoanStatus: false,
    addLoanError: "",
    loans:[],
    loansLoading:false,
    fetchLoansError:"",
    updateLoanStatus: false,
    updateLoanError: "",
    loanPaymentStatus:false,
    loanPaymentError:"",
    count_riders:"",
    count_ridersLoading:false,
    count_ridersError:"",
    count_agents:"",
    count_agentsLoading:false,
    count_agentsError:"",
    count_loans:"",
    count_loansLoading:false,
    count_loansError:"",
    paid:[],
    paid_loading:false,
    paid_Error:"",
    unpaid:[],
    unpaid_loading:false,
    unpaid_Error:"",
    addExpenseStatus: false,
    addExpenseError: "",
    expenses:[],
    expensesLoading:false,
    fetchExpensesError:"",
    updateExpenseStatus: false,
    updateExpenseError: "",
    deleteExpenseStatus: false,
    deleteExpenseError: "",
    addSavingStatus: false,
    addSavingError: "",
    savings:[],
    savingsLoading:false,
    fetchSavingsError:"",
    updateSavingStatus: false,
    updateSavingError: "",
    deleteSavingStatus: false,
    deleteSavingError: "",
    deleteLoanStatus: false,
    deleteLoanError: "",
}